# Generated by Django 4.1.3 on 2024-04-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungoals_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cheatcode',
            new_name='e',
        ),
    ]
