# Generated by Django 4.1.3 on 2024-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungoals_app', '0002_rename_cheatcode_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='sup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
